# Workflow - build, publish jar and image to GitHub Packages for all
name: deploy-all-workflow

on:
  workflow_dispatch:
    inputs:
      skip-test:
        required: true
        type: boolean
        default: false
  workflow_call:
    inputs:
      skip-test:
        required: true
        type: boolean
        default: false

jobs:
  parent:
    uses: ./.github/workflows/deploy-job.yml
    with:
      repo: extact-io/msa-rms-parent
      skip-test: ${{ inputs.skip-test }}
    secrets: inherit

  platform:
    needs: parent
    uses: ./.github/workflows/deploy-job.yml
    with:
      repo: extact-io/msa-rms-platform
      skip-test: ${{ inputs.skip-test }}
    secrets: inherit

  apigateway:
    needs: platform
    uses: ./.github/workflows/deploy-job.yml
    with:
      repo: extact-io/msa-rms-apigateway
      skip-test: ${{ inputs.skip-test }}
      with-image: true
      deploy-type: ec2
      aws-appname: msa-apigateway
    secrets: inherit

  service-item:
    needs: platform
    uses: ./.github/workflows/deploy-job.yml
    with:
      repo: extact-io/msa-rms-service-item
      skip-test: ${{ inputs.skip-test }}
      with-image: true
    secrets: inherit

  service-reservation:
    needs: platform
    uses: ./.github/workflows/deploy-job.yml
    with:
      repo: extact-io/msa-rms-service-reservation
      skip-test: ${{ inputs.skip-test }}
      with-image: true
    secrets: inherit

  service-user:
    needs: platform
    uses: ./.github/workflows/deploy-job.yml
    with:
      repo: extact-io/msa-rms-service-user
      skip-test: ${{ inputs.skip-test }}
      with-image: true
    secrets: inherit

  ui-console:
    needs: platform
    uses: ./.github/workflows/deploy-job.yml
    with:
      repo: extact-io/msa-rms-ui-console
      skip-test: ${{ inputs.skip-test }}
    secrets: inherit
