# Common JOB called from msa-rms-parent own workflow
name: deploy-job-self

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      with_image:
        type: boolean
        default: false

defaults:
  run:
    working-directory: build

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo }}
        path: build
    - name: Set up JDK 17 for GitHub
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
    - if: inputs.with_image
      name: prepare IMAGE_TAG
      run: echo "IMAGE_TAG=`git show --format='%H' --no-patch`" >> $GITHUB_ENV
    - if: inputs.with_image
      name: Publish jar to GitHub Packages and Build Image
      run: |
        mvn -B -Pcli,copy-libs \
          deploy \
          docker:build \
          -Dimage.tag=$IMAGE_TAG \
          -DskipTests \
          -s $GITHUB_WORKSPACE/settings.xml 
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - if: inputs.with_image
      name: Set up JDK 17 for GitHub
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: ghcr.io
        server-username: REPOSITORY_SERVER_USER
        server-password: REPOSITORY_SERVER_PASSWORD
        settings-path: ${{ github.workspace }}
    - if: inputs.with_image
      run: cat $GITHUB_WORKSPACE/settings.xml
    - if: inputs.with_image
      name: Push Image to GitHub Packages
      run: |
        mvn -B -X docker:push -Dimage.tag=$IMAGE_TAG -s $GITHUB_WORKSPACE/settings.xml
      env:
        REPOSITORY_SERVER_USER: ${{ secrets.REPOSITORY_SERVER_USER }}
        REPOSITORY_SERVER_PASSWORD: ${{ secrets.REPOSITORY_SERVER_PASSWORD }}
    - if: ${{ !inputs.with_image }}
      name: Publish jar to GitHub Packages
      run: mvn -B -Pcli deploy -DskipTests -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
