name: test-upload

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - '**/test-upload.yml'

jobs:
  upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build
    steps:
    - uses: actions/checkout@v3
      with:
        path: build
    - name: Output IMAGE_TAG to file
      run: git show --format='%H' --no-patch > image_tag
    - name: Upload build Artifact of IMAGE_TAG
      uses: actions/upload-artifact@v3
      with:
        name: image_tag_file
        path: build/image_tag
        retention-days: 1

  download:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build
    steps:
    - name: Download build Artifact of IMAGE_TAG
      uses: actions/download-artifact@v3
      with:
        name: image_tag_file
        path: build
    - name: test file
      run: cat image_tag

